baseurl: 
permalink: pretty
markdown: kramdown
prose:
  rooturl: ''
  siteurl: 'https://beta.leadiq.com/blog/'
  relativeLinks: 'https://beta.leadiq.com/blog/links.jsonp'
  media: 'LeadIQ/ClientApp/public/img'
  metadata:
    LeadIQ/ClientApp/src/blogs:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "coverImage"
        field:
          element: "text"
          label: "Cover Image Name"
          value: ""
      - name: "publishDate"
        field:
          element: "text"
          label: "Publish Date"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "authorProfile"
        field:
          element: "textarea"
          label: "Author Profile"
          value: ""
      - name: "authorImage"
        field:
          element: "text"
          label: "Author Image"
          value: ""
      - name: "metaTitle"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "metaDescription"
        field:
          element: "text"
          label: "Meta Description"
          value: ""
      - name: "metaKeywords"
        field:
          element: "text"
          label: "Meta Keywords"
          value: ""
    LeadIQ/ClientApp/src/podcasts:
      - name: "layout"
        field:
          element: "hidden"
          value: "podcast"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          value: ""
      - name: "coverImage"
        field:
          element: "text"
          label: "Cover Image Name"
          value: ""
      - name: "webImage"
        field:
          element: "text"
          label: "Web Image Name"
          value: ""
      - name: "refLink"
        field:
          element: "text"
          label: "Reference Link"
          value: ""
      - name: "audioLinks"
        field:
          element: "text"
          label: "Audio Links"
          value: ""
      - name: "published"
        field:
          element: "text"
          label: "Published"
          value: ""
      - name: "metaTitle"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "metaDescription"
        field:
          element: "text"
          label: "Meta Description"
          value: ""
      - name: "metaKeywords"
        field:
          element: "text"
          label: "Meta Keywords"
          value: ""

