baseurl: /LeadIQ/ClientApp/src/blogs/
permalink: pretty
markdown: kramdown
prose:
  rooturl: 'LeadIQ/ClientApp/src/'
  siteurl: 'https://beta.leadiq.com/blog/'
  relativeLinks: 'https://beta.leadiq.com/blog/links.jsonp'
  media: 'media'
  metadata:
    blogs:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"