import React from 'react';
import GetStarted from '../components/buttons/GetStarted';

class MasterServiceAgreement extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            displayPolicy: false,
            width: 0
        };
    }

    componentDidMount() {
        if (window.outerWidth < 1024) {
            this.setState({
                width: window.outerWidth,
                displayPolicy: true
            })
        } else {
            this.setState({
                width: window.outerWidth
            })
        }
        window.scrollTo(0, 0);
    }

    render() {
        return (
            <div>
                <div>
                    <div className="service-cover">
                        <div className="container prospectHeaderTitle">
                            <section className="pt-5 gettingStarted">
                                <h1 className="text-white text-center  mb-4 fa-2x prospectText"><b>Master Service Agreement</b></h1>
                                <h4 className="text-white text-center chromeText mb-4">This Master Subscription Agreement governs customer's use of LeadIQ services. If Customer registers for a free trial of LeadIQ services or free services, the applicable provisions of this agreement will also govern that free trial or those free services.</h4>
                                <div className="justify-content-center d-flex">
                                    <GetStarted size="lg" />
                                </div>
                            </section>
                        </div>

                    </div>
                    <div className="faq-waveDesign">
                        <img src="/img/wave-four.png" className="img-fluied faq-waveDesignProspect" alt="wave" />
                    </div>
                </div>

                <div className="blog-container">
                    <div className="container">
                        <div className="card">
                            <div className="card-body card-blog">
                                <h4 className="liq-text-primary text-center pb-4">Lead  IQ,  Inc.SAAS  Agreement</h4>
                                <p>Page  1LEAD  IQSAAS  AGREEMENT  Lead  IQ,  Inc.(“Company”),  a  California  corporation  shall  provide  access  to  the  licensed  software  and  services  offered  via  the leadiq.io website(hereinafter  collectively  known  as  the  “Licensed  Software”).    You,  the  client  (“Client”),  wishto  use  the  Company’s  Licensed  Software  in  accordance  with  this  Agreement  (“Agreement”).    This  Agreement  defines  the  relationship  between  Company  and  Client  (collectively  referred  to  as  the  “Parties”  or  in  the  singular  as  “Party).    By  clicking  “I  agree”  or  by  usingthe  Licensed  Software,  Client  agrees  to  be  bound  by  this  Agreement,  the  Lead  IQ  Terms  of  Serviceand  Privacy  Policy,  and  any  other  relevant  agreements  related  to  Client’s  use  of  the  Licensed  Software.  PLEASE  BE  AWARE  THAT  THERE  ARE  ARBITRATION  PROVISIONS  IN  THIS  AGREEMENT  THAT  MAY  AFFECT  YOUR  RIGHTS</p>
                                <h4 className="liq-text-primary">1. INTRODUCTION</h4>
                                <h5 className="liq-text-primary">1.1 Softwareand  Ownership.</h5>
                                <p>Companyowns  the  proprietary  computer  software  application  known  as  the  Licensed  Softwarethat  allows  Clientto  build  a  list  of  leads  and  contact  information</p>
                                <h5 className="liq-text-primary">1.2 Client’sDesiredUse.</h5>
                                <p>Clientdesiresto  obtain  a  subscription  to  use  Company’s  Licensed  Software  by  remote  access  to  a  computing  environment  controlledandhosted  by  a  third  partydatacenter  in  accordance  with  the  terms  and  conditions  of  this  Agreement.  The  Licensed  Software  is  intended  to  be  used  by  representatives,  employees,  or  other  authorized  users  (as  defined  in  this  Agreement).    Specifically,  theLicensed  Software  allows  Client  to  contact  and  capture  marketing  leads  through  the  Licensed  Software</p>
                                <h4 className="liq-text-primary">2. SUBSCRIPTION  FOR  LICENSED  RIGHTS</h4>
                                <h5 className="liq-text-primary">2.1 Subscription  for  License</h5>
                                <p>Companyhereby  grants  to  Client,  and  Clienthereby  accepts  from  Company,  during  the  term  of  this  Agreement  and  subject  to  compliance  by  Clientwith  the  terms  and  conditions  hereof,  a  nonexclusive,  limited,  revocable,  nontransferable  license  for  Clientto  access  and  use  the  Licensed  Software.  All  rights  not  expressly  granted  in  this  Agreement  are  hereby  expressly  reserved  by  Company.</p>
                                <h5 className="liq-text-primary">2.2Restrictions  on  Licensed  Rights</h5>
                                <p>Clientacknowledges  that  the  Licensed  Software  is  subject  to  copyrights  owned  by  Companyand  its  licensors.  Clientis  prohibited  from  copying,  duplicating,  or  permitting  anyone  else  to  copy  or  duplicate  the  Licensed  Software  or  any  module  or  other  portion  thereof.    Clientis  further  prohibited  from  (a)  using  the  Licensed  Software  to  process  any  data,other  than  Client's  own  data,and  (b)  from  modifying,  adapting,  or  creating  derivative  works  based  on  the  Licensed  Software.  Clientacknowledges  that  the  Licensed  Software  contains  information  that  is  confidential  and  proprietary  to  Companyand  its  licensors,  and  whichderives  independent  economic  value,  actual  or  potential,  from  not  being  generally  known  to,  and  not  being  readily  ascertainable  by  proper  means  byother  persons  who  can  obtain  economic  value  from  their  disclosure  or  use,and  is  the  subject  of  efforts  by  Companythat  are  reasonable  under  the  circumstances  to  maintain  its  secrecy.  Clientis  expressly  prohibited  from  reverse  engineering,  reverse  compiling,  disassembling,or  otherwise  deriving  the  source  code  for  the  Licensed  Software. </p>
                                <h5 className="liq-text-primary">2.3 Access  Procedures.</h5>
                                <p>Clientshall  either  create,  or  be  assigned,a  unique  username.In  addition,  Clientmaybe  given  the  opportunity  to  formulate  unique  usernames  and  passwords  for  the  individuals  whom  Clientauthorizes  to  access  and  use  the  Licensed  Software.  Clientshall  also  have  the  opportunity  to  change,  or  to  require  its  users  to  change,  such  passwords  from  time  to  time  in  accordance  with  Client's  own  internal  security  policies.  Clientacknowledges  and  agrees  that  Clientand  the  individuals  Clientauthorizes  to  access  and  use  the  Licensed  Software  shall  be  responsible  for  maintaining  the  confidentiality  of  the  usernamesand  passwords,  and  Clientshall  be  liable  for  any  consequences  that  may  result  from  their  disclosure,  including  but  not  limited  to  any  resulting  access  to,  use  of,  or  modification  of  the  Licensed  Software  and  access  to,  integrity  of  and  loss  of  the  Client’sdata  that  can  be  accessed  using  the  Licensed  Software. </p>
                                <h5 className="liq-text-primary">2.4 No  Access  to  Persons  Under  18;  ClientObligation  to  Deny  Access.</h5>
                                <p>Client  agrees  that  it  is  solely  responsible  for  providing  and  restricting  access  to  the  Licensed  Softwareto  any  authorized  users,  as  required  by  this  Agreement.  Clientmust  ensure  that  allauthorized  users  and  guests  thatuse  the  Licensed  Software  are  above  the  age  of  18</p>
                                <h5 className="liq-text-primary">2.5 Computing  Environment</h5>
                                <p>Clientacknowledges  that  the  Licensed  Software  resides  in  a  third  partyhosting  company’scomputing  environment,  which  comprises  both  servers  and  telecommunications  services,  and  that  certain  uses  of  the  capabilities  offered  by  the  Licensed  Software  may  render  the  Licensed  Software  inaccessible  or  may  impair  the  performance  of  thee  computing  environment  for  Clientand/or  Company's  other  Clients.  In  the  event  of  any  such  use  by  Client,  Companyshall  so  notify  Clientand  Clientshall  be  obligated  to  put  an  immediate  stop  to  such  useand  will  notify  Company,  in  writing,  that  it  has  stopped  such  use.  In  the  event  of  Client’s  failure  to  put  an  immediate  stop  to  such  use,  Companyreserves  the  right  to  terminate  Client’s  access  to  the  Licensed  Software. </p>
                                <h5 className="liq-text-primary">2.6 Prohibited  Use  of  Licensed  Software;  Rules  of  Use</h5>
                                <p>Clientshall  not  cause  or  allow  submission  of  any  data  or  information  to  Companyor  the  Licensed  Software  of  any  illegal,  misleading,  defamatory,  obscene,  profane,  confidential  or  proprietary  to  third  parties,  or  inconsistent  with  the  non-religious  and  non-political  purposes  of  the  Licensed  Softwareas  determined  by  Company.  Also,  Clientshall  not  use  the  Licensed  Software  for  any  illegal  purpose,  including  but  not  limited  to,  uses  in  violation  of  Can-Spam,TCPA,or  violates  anyotherprivacy  laws.  Companymay  enact  and  enforce  reasonable  rules  of  use  as  promulgated  and  amended  from-to-time  by  Companyregulating  the  use  of  the  Licensed  Software  by  Clientand  its  users,  and  Clientagrees  to  be  bound  by  such  rules.  Breach  of  such  rules  or  this  section  may  result  in  the  offending  information  being  removed  by  Companyor  termination  of  this  Agreement.</p>
                                <h5 className="liq-text-primary">2.7 No  Resale  or  Sublicensing  of  Licensed  Software.</h5>
                                <p>Companyprovides  the  Licensed  Software  for  the  Client’s  use  and  the  use  of  Client’s  authorized  users  andguests.  However,  Clientshall  not  resell,  sublicense,  assign  or  otherwise  allow  the  use  of  the  Licensed  Software  by  or  for  the  benefit  of  any  other  person,  entity  or  group  without  the  express  written  approval  of  Company.</p>
                                <h4 className="liq-text-primary">3. MAINTENANCE</h4>
                                <h5 className="liq-text-primary">3.1 Operational  Support</h5>
                                <p>Company,  may  at  its  sole  discretion,  makemaintenance  support  staff  available  during  reasonable  business  hoursPacific  Standard  Time  Monday  through  Friday,  excluding  Holidays,to  answer  questions  by  telephone  and  email  regarding  the  Licensed  Software  from  any  of  the  Client’s  representatives.    </p>
                                <h5 className="liq-text-primary">3.2 Error  Investigation</h5>
                                <p>In  the  event  that  the  Licensed  Software  becomes  inaccessible  or  deviates  from  normal  usage  patterns,  Clientshall  give  Companywritten  notification  of  the  inaccessibility  or  the  deviation,  and  in  the  case  of  deviations,  sufficient  information  to  permit  replication  and  analysis.  Upon  receipt  of  notice  from  Clientof  any  inaccessibility  or  deviation,  Companyshall  use  efforts  that  it  considers  to  be  reasonable  in  its  sole  discretion  to  diagnose  the  cause  of  the  inaccessibility  or  deviation.  Upon  completion  of  the  diagnosis,  Companyshall  advise  Clientof  the  cause  of  the  inaccessibility  or  deviation  and  shall  use  effortsthat  it  considers  to  be  reasonable  in  its  sole  discretion,  without  charge,  to  restore  access  to  the  Licensed  Software  or  to  correct  or  avoid  the  deviation.    Notwithstanding  the  foregoing,  Companyshall  have  no  obligation  to  resolve  any  inaccessibility  or  deviation  caused  by  (a)  modification  of  the  Licensed  Software  by  anyone  other  than  Company,  (b)  use  of  the  Licensed  Software  for  any  purpose  other  than  intended,  (c)  misuse  or  incorrect  use  of  the  Licensed  Software,  or  (d)  malfunction  of  any  Clientcomputer  or  any  telecommunications  services  not  under  the  control  of  Company</p>
                                <h5 className="liq-text-primary">3.3 Data  Maintenance.</h5>
                                <p>It  shall  be  the  responsibility  of  Company  to  implement  the  data  archive  procedures  resident  in  the  Licensed  Software  at  regular  intervals,  and  Client  acknowledges  that  theliability  for  loss,  destruction  or  damage  to  any  data  Client  may  store  in  Company’s  computing  environment  is  limited  pursuant  to  this  Agreement  and  the  hosting  provider  agreement.</p>
                                <h5 className="liq-text-primary">3.4 Database  Maintenance</h5>
                                <p>Client  agrees  that  it  is  solely  responsible  for  maintaining  any  physical  or  electronic  records  that  it  has  access  to  through  the  Licensed  Software.  Client  acknowledges  that  the  liability  for  loss,  destruction  or  damage  to  any  databases  Client  may  have  access  toislimited  pursuant  to  this  Agreement  and  any  third  partyhosting  provider  agreements.</p>
                                <h5 className="liq-text-primary">3.5 Enhancements</h5>
                                <p>Companyreserves  the  right,  as  reasonably  necessary  or  convenient  for  Company’s  own  purposesand  at  its  sole  discretionto  improve  the  quality  of  the  Licensed  Software,  to  change  access  procedures,  types  of  equipment  utilized  in  the  Companycomputing  environment,  system  interfaces,  operating  and  other  system  and  network  software,  utilities,  and  database  software,  and  to  implement  enhancementsto  the  Licensed  Software.  This  section  does  not  obligate  Company  to  make  any  enhancements  to  the  Licensed  Software.</p>
                                <h5 className="liq-text-primary">3.6 Uptime  Guarantees  and  Access  Interruptions</h5>
                                <p>Company  shall  make  the  Licensed  Software  available  at  all  times,as  reasonably  possibleand  practicable;  however,  Company  makes  no  guarantees  regarding  the  uptime  of  the  Licensed  Software.Clientacknowledges  and  agrees  that  in  order  for  Companyto  perform  the  maintenance  services  set  forth  herein,  Companyor  its  hosting  providermay  be  required  from  time  to  time  to  interrupt  Client's  ability  to  access  the  Licensed  Software.  Insofar  as  practicable,  Companyshall  confine  such  interruptions  to  scheduled  interruptions  and  give  Clientat  least  twenty-four(24)  hours  noticeof  a  scheduled  interruption.     </p>
                                <h4 className="liq-text-primary">4. ADDITIONAL  AGREEMENTS</h4>
                                <h5 className="liq-text-primary">4.1Additional  Agreements</h5>
                                <p>Client  and  Company  agree  that  the  Parties  may  be  required  to  agree  to  the  Company’s  Terms  of  Service,  Privacy  Policy,  or  other  agreements  in  order  to  facilitate  Client’s  use  of  the  Licensed  Software.</p>
                                <h5 className="liq-text-primary">4.2 Order  Forms</h5>
                                <p>Company  and  Client  may  execute  an  order  form  (“Order  Form”)  which  shallmodify  the  terms  of  this  Agreement.    In  the  event  that  Company  and  Client  have  executed  an  Order  Form,  the  terms  of  the  Order  Form  shall  control  and  be  binding  and  supersede  any  directly  conflicting  terms  within  this  Agreement.    In  the  event  there  is  an  ambiguity  arising  between  the  Order  Form  and  this  Agreement,  Company  shall  have  the  sole  discretion  in  deciding  the  interpretation  of  any  such  ambiguity.</p>
                                <h4 className="liq-text-primary">5. PAYMENTS</h4>
                                <h5 className="liq-text-primary">5.1 Payment  ofSubscription  Rates</h5>
                                <p>In  consideration  ofthe  license  granted  in  this  Agreement,  Clientshall  pay  the  subscription  rate(“Subscription  Rate”)as  displayed  at  the  purchase  screen  forthe  Licensed  Software  per  monthor  annually(“Subscription  Period”)as  selected  by  the  Client.  The  Subscription  Rateshall  be  due  and  payable  upon  the  beginning  of  each  and  any  subscription  period,  and  upon  expiryof  any  free  Trial  Period(s),  as  specified  below.Client  may  cancel  the  subscription  at  any  time  by  notifying  Companyin  writingthat  it  no  longer  wishes  to  pay  the  Subscription  Rate.In  the  event  that  Client  and  Company  have  executed  an  Order  Form,  the  Order  Form  shall  dictate  all  payment  terms.</p>
                                <h5 className="liq-text-primary">5.2 Automatic  Renewaland  Payment</h5>
                                <p>Client  agrees  and  expressly  consents  to  Company  automatically  renewing  andcharging  the  Subscription  Ratefor  each  consecutive  Subscription  Period.  Client  may  terminate  the  subscription  at  any  time  by  providing  written  notice  to  the  Company.</p>
                                <h5 className="liq-text-primary">5.3 Taxes</h5>
                                <p>All  amounts  described  herein  are  exclusive  of  all  federal,  state,  municipal  or  other  governmental  excise,  sales,  value-added,  or  other  taxes  or  other  withholding  obligations  and  levies  now  in  force  or  enacted  in  the  future  and,  accordingly,  the  amount  ofall  payments  hereunder  is  subject  to  an  increase  equal  to  the  amount  of  any  tax  Companymay  be  required  to  collect  or  pay  in  connection  with  the  Licensed  Software  and  related  services  other  than  any  tax  on  the  net  income  of  Company.</p>
                                <h5 className="liq-text-primary">5.4 Payment  Termsand  Renewals</h5>
                                <p>All  amounts  due  and  payable  to  Companyhereunder  shall  be  remitted  by  Clientat  the  time  of  Client’s  subscription  or  renewal.Payment  shall  be  made  in  US  dollars  andin  any  methods  permitted  via  the  Licensed  Software.Continued  use  of  the  Licensed  Software  by  Clientor  its  authorized  users  or  guests  shall  automatically  renew  Client’s  subscription  at  the  Subscription  Rates  then  in  effect.Client  agrees  that  failure  to  timely  pay  Company  may  result  in  immediate  inaccessibility  to  the  Licensed  Software  and  deletion  of  Client  data.    Company  cannot  be  responsible  for  any  losses  experienced  by  Client  in  the  event  of  Client’s  failure  to  pay.</p>
                                <h5 className="liq-text-primary">5.5 TrialPeriod</h5>
                                <p>Clientmay  be  offered  a  free  trial  period  (“Trial  Period”)  touse  the  Licensed  Software  without  any  Subscription  Rate  charges,  this  Trial  Period  will  begin  on  the  date  where  this  Agreement  is  accepted  by  Client  and  shall  continue  until  the  Trial  Period  expires.    After  the  Trial  Period  expiration,  Clientwill  be  charged  the  Subscription  Rates  according  to  this  Agreementor  as  displayed  on  the  Licensed  Software  unless  Client  cancels  its  use  of  the  Licensed  Software  byproviding  noticeof  cancellationto  the  Companywithin  the  Trial  Period.</p>
                                <h5 className="liq-text-primary">5.6 Refund  Period</h5>
                                <p>Upon  expiry  of  the  Trial  Period,  if  any,Client’s  subscription  shall  begin.After  the  expiration  of  the  Trial  Period,  Client  shall  have  fifteen  (15)  calendar  days  to  cancel  its  subscription  and  shall  receive  a  full  refund  (“Refund  Period”). In  order  to  cancel Lead  IQ,  Inc.SAAS  AgreementPage  5and  to  receive  a  refund  during  the  Refund  Period,  Client  must  contact  Company  or  cancel  the  subscription  usingClient’s  account  dashboard.  After  such  Refund  Period  no  refunds  shall  be  granted.</p>
                                <h5 className="liq-text-primary">5.7 Subscription  Rate  Increase.</h5>
                                <p>From  time  to  time  Company  may  deem  it  necessary  to  increase  the  Subscription  Rate.    In  the  event  of  a  Subscription  Rate  increase,  Company  shall  provide  Client  written  notice  of  such  an  increase  and  the  period  where  such  increase  shall  be  implemented.  In  order  for  Client  to  continue  using  the  Licensed  Software,  Client  must  agree  to  such  an  increase  and  any  other  relevant  terms.</p>
                                <h4 className="liq-text-primary">6. OWNERSHIP</h4>
                                <h5 className="liq-text-primary">6.1 Licensed  Software</h5>
                                <p>The  components  of  the  Licensed  Software  are  subject  to  copyrights  and  other  proprietary  rights  of  Companyand  its  licensors.  All  rights,  title  and  interest  in  and  to  the  Licensed  Softwareand  any  and  all  modifications  thereto,which  are  prepared  by  or  for  Company,shall  not  pass  to  Client,  but  shall  remain  with  Companyand  its  licensors.    Companyshall  be  the  sole  owner  of  all  inventions,  discoveries,  improvements,  or  enhancements  relating  to  the  Licensed  Software  (including  without  limitation  any  work  of  authorship  that  constitutes  a  "derivative  work"  of  the  Licensed  Software  within  the  meaning  of  the  definition  set  forth  in  Section  101  of  the  U.S.  Copyright  Act),  whether  in  written  or  unwritten  form,  that  are  developed  by  Company.</p>
                                <h5 className="liq-text-primary">6.2 ClientData</h5>
                                <p>Any  Clientdata  that  is  collected  or  generated  through  use  of  the  Licensed  Software  on  Company’s  server  shall  be  secured  using  industry  standard  security;  however,Company  makes  no  guarantees  that  such  information  can  or  will  remain  confidential.Clientshall  be  responsible  for  the  accuracy  and  legality  of  any  Clientdata.  Clienthereby  grants  to  Companya  nonexclusive,  perpetual,  worldwide,  paid-up  license  to  use  Clientdata  that  is  collected  or  generated  through  use  of  the  Licensed  Software  on  Company’s  server  to  perform  Company’s  obligations  under  this  Agreement  and  to  analyze,  transfer  and  use  such  Clientdata,  and  to  disclose  and  distribute  Clientdata,  in  an  aggregated  form  from  which  all  personally  identifiable  information  has  been  removed,  for  purposes  of  benchmarking  system  performance,  preparing  statistics  and  system  metrics,  marketing  and  other  purposes. </p>
                                <h5 className="liq-text-primary">6.3 Unauthorized  Use</h5>
                                <p>(a)  Clientagrees  to  notify  Companyimmediately  of  the  unauthorized  possession,  use,  or  knowledge  of  any  component  of  the  Licensed  Software  to  which  Clientor  its  authorized  usersor  guests  is  given  access  under  this  Agreement  and  of  other  information  made  available  to  Clientunder  this  Agreement,  by  any  person  or  organization  not  authorized  by  this  Agreement  to  have  such  possession,  use  or  knowledge.  Clientwill  promptly  furnish  full  detailsof  such  possession,  use  or  knowledge  to  Company,  will  assist  in  preventing  the  recurrence  of  such  possession,  use  or  knowledge,  and  will  cooperate  with  Company,  at  Company’s  expense,  in  any  litigation  against  third  partiesdeemed  necessary  by  Companyto  protect  its  proprietary  rights.  Client's  compliance  with  this  Section  shall  not  be  construed  in  any  way  as  a  waiver  of  any  right  by  Companyto  recover  damages  or  obtain  other  relief  against  Clientfor  any  act  or  omission  which  may  have  resulted  in  the  unauthorized  possession,  use  or  disclosure.   </p>
                                <p>(b)  Companyagrees  to  notify  Clientwithin  twenty  four  (24)  hoursof  the  knowledge  of  unauthorized  possession,  use,  or  knowledge  of  any  Clientdata  furnished  to  Companyby  Clientor  otherwise  accessible  by  Companyunder  this  Agreement  and  of  other information  made  available  to  Clientunder  this  Agreement,  by  any  person  or  organization  not  authorized  by  this  Agreement  to  have  such  possession,  use  or  knowledge.    Companywill  promptly  furnish  full  details  of  such  possession,  use  or  knowledge  to  Client,  will  assist  in  preventing  the  recurrence  of  such  possession,  use  or  knowledge,  and  will  cooperate  with  Client,  at  Client’s  expense,  in  any  litigation  against  third  partiesdeemed  necessary  by  Clientto  protect  its  proprietary  rights.  Company's  compliance  with  this  Section  shall  not  be  construed  in  any  way  as  a  waiver  of  any  right  by  Clientto  recover  damages  or  obtain  other  relief  against  Companyfor  any  act  or  omission  which  may  have  resulted  in  the  unauthorized  possession,  use  or  disclosure.  </p>
                                <h4>7. CREDITS</h4>
                                <h5 className="liq-text-primary">7.1 Licensed  Software  Credits</h5>
                                <p>Company  may  make  credits  available  via  the  Licensed  Software  for  Client  to  use  to  redeem  for  services.    Client  understands  that  these  credits  have  no  cash  valueand  are  not  redeemable  for  cash  or  any  other  equivalent  currency.  Depending  on  subscriptionplanselected  Client  shall  havea  set  number  ofcredits  available  to  use  per  Subscription  Period.    Information  regarding  the  amount  of  credits  givento  Clientper  Subscription  Period  can  be  found  on  the Leadiq.io website  or  via  the  Client’s  account  dashboard  on  the  Licensed  Software.      Credits  shall  be  divided  into  two  categories:  Capture  Credits  and  Email  Credits  (defined  below).</p>
                                <h5 className="liq-text-primary">7.2 Capture  Credits</h5>
                                <p>"Capture  Credits"  shall  mean  a  credit  that  may  be  redeemed  for  an  actual  lead  captured  by  Client  using  the  Licensed  Software.   </p>
                                <h5 className="liq-text-primary">7.3 Email  Credits</h5>
                                <p>“Email  Credits”  shall  mean  a  credit  that  may  be  redeemed  for  each  valid  email  address  provided  by  the  Licensed  Software.</p>
                                <h5 className="liq-text-primary">7.4 Redeeming  Credits</h5>
                                <p>Client  shall  be  assigned  a  specific  number  of  Capture  Credits  and  Email  Credits  according  to  its  subscription  planper  Subscription  Period.    Client  may  redeem  either  the  Capture  or  Email  Credits  via  the  Licensed  Software  by  providing  information  requiredand  issuing  a  request.    Upon  receipt  of  a  request  to  redeem  credits,  the  Licensed  Software  shall  provide  any  available  information  requested  by  Client.    Email  Credits  shall  be  deemed  to  be  used  when  the  Licensed  Software  delivers  anemail  address  for  a  Client  request.    Capture  Credits  shall  be  deemed  used  when  an  actual  Client  lead  is  captured  and  Client  has  received  response  from  suchpotential  lead.    In  the  event,  that  a  Client  credit  request  cannot  be  processed,  for  any  reason  whatsoever,  nocredits  shall  be  deducted  from  the  Client’s  credit  pool.</p>
                                <h5 className="liq-text-primary">7.5 No  Rollover  of  Credits</h5>
                                <p>Both  Capture  Credits  and  Email  Credits  will  be  set  at  a  fixed  number  at  the  beginning  ofeach  Subscription  Period  based  on  the  Subscription  Rate  paid.    All  Capture  Credits  and  Email  Credits  must  be  used  within  the  Subscription  Period.    After  the  expiration  of  the  Subscription  Period,  all  unused  Capture  Credits  and  Email  Credits  shall  be  forfeited  and  may  not  be  rolled  over  or  redeemed  during  the  subsequent  Subscription  Period.</p>
                                <h4 className="liq-text-primary">8. DISCLAIMER</h4>
                                <h5 className="liq-text-primary">8.1 Exclusive  Remedy</h5>
                                <p>In  the  event  of  any  failure  by  the  Licensed  Software  to  perform,  in  any  material  respect,  in  accordance  with  any  warranties  setforth  hereinin  this  Agreement,  the  only  liability  of  Companyto  Client,  and  Client's  sole  and  exclusive  remedy,  shall  be  to  cancel  Client’s  subscription  and  seek  any  remedies  made  available  via  this  Agreement</p>
                                <h5 className="liq-text-primary">8.2 Disclaimers</h5>
                                <p><b>THE  LICENSED  SOFTWARE  IS  OFFERED  “AS  IS”.  COMPANYHEREBY  DISCLAIMS,  ALL  WARRANTIES,  EXPRESS  AND  IMPLIED,  INCLUDING  WITHOUT  LIMITATION  ANY  IMPLIED  WARRANTIES  OF  MERCHANTABILITY,  FITNESS  OF  THE  LICENSED  SOFTWARE  FOR  A  PARTICULAR  PURPOSE  AND  NON-INFRINGEMENT.  COMPANYAND  ITS  LICENSORS  DO  NOT  WARRANT  THAT  THE  LICENSED  SOFTWARE  WILL  BE  UNINTERRUPTED,  BUG-FREE,  VIRUS-FREE,OR  ERROR-FREE  OR  THAT  THE  DATA  OR  OTHER  RESULTS  GENERATED  BY  THE  LICENSED  SOFTWARE  WILL  BE  ACCURATE  OR  COMPLETE.  IT  IS  THE  RESPONSIBILITY  OF  CLIENTTO  EVALUATE  THE  ACCURACY,  COMPLETENESS,  OR  USEFULNESS  OF  ALL  DATA  AND  RESULTS  GENERATED  THROUGH  THE  USE  OF  THE  LICENSED  SOFTWARE.</b></p>
                                <h4 className="liq-text-primary">9. DISPUTES,  ARBITRATION;  INDEMNIFICATION</h4>
                                <h5 className="liq-text-primary">9.1 Disputes  Generally</h5>
                                <p>The  Partieshereby  undertake  to  use  good  faith  efforts  to  settle  all  disputes  arising  under  this  Agreement.  Failing  settlement,  all  disputes,  including  without  limitation  claims  of  breach  of  contract,  fraud  in  the  inducement  and  negligence,  shall  be  referred  to  binding  arbitration  in  Santa  Clara,  Californiain  accordance  with  the  Commercial  Rules  of  Arbitration  of  the  American  Arbitration  Association.      Such  arbitration  shall  take  place  without  personal  appearance  and  any  filings  done  via  paper  or  electronic  and  arguments  via  telephonic  conference. </p>
                                <h5 className="liq-text-primary">9.2 Arbitrator</h5>
                                <p>The  Partiesshall  use  their  best  efforts  to  appoint  an  arbitrator  who  is  knowledgeable  in  computer  technology  within  seven  (7)  days  after  receipt  by  one  Partyof  the  other  Party's  notice  of  intention  to  arbitrate.    If  the  Partiesare  unable  to  agree  on  a  single  arbitrator  within  such  period,  either  Partymay  request  appointment  of  an  arbitrator  by  the  American  Arbitration  Association,  and  the  arbitrator  so  appointed  shall  be  the  sole  arbitrator.  The  decision  of  the  arbitrator  shall  be  final  and  may  be  enforced  in  any  court  of  competent  jurisdiction.    </p>
                                <h5 className="liq-text-primary">9.3 Expense  of  Arbitration</h5>
                                <p>Each  Partyshall  be  solely  responsible  for  any  fees  related  to  any  actions  brought  via  arbitration.</p>
                                <h5 className="liq-text-primary">9.4 Indemnification</h5>
                                <p>Clientagreesthat  Clientwill  indemnify  and  defend  Companyand  its  directors,  officers,  employees,  agents,members,vendors,  or  contractors  against  any  liabilities,  including  reasonable  attorneys’  fees  and  court  fees  and  disbursements,  which  arise  from  or  related  to  Client’s  use  of  the  Licensed  Software  or  any  associated  services.    Clientalso  agrees  to  indemnify  Companyfor  Client’sfailure  to  abide  by  this  Agreement,  any  negligent  or  intentional  wrongdoing  by  anyone  who  uses  Client’saccountor  subaccount,  and  any  act  or  omission  of  Client’swith  respect  to  the  payment  of  any  fees  owing  to  Company.    We  reserve  the  right  to  report  any  wrongdoing  of  Clientto  any  applicable  government  agencies  or  otherwise  (but  are  not  required  to).  In  addition,  these  terms  do  not  create  a  private  cause  of  action  between  users  nor  do  they  require  us  to  take  action  against  any  user  simply  because  Clientfeels  a  usermay  have  violated  a  provision  of  these  terms.    We  reserve  the  right  to  dictate  the  defense  and  settlement  of  anyaction  in  which  Client  isresponsible  for,  including  the  choice  of  counsel. </p>
                                <h4 className="liq-text-primary">10. TERM  AND  TERMINATION</h4>
                                <h5 className="liq-text-primary">10.1 Initial  Term;  Renewal</h5>
                                <p>The  term  of  this  Agreement  shall  commence  upon  the  Effective  Date  ofthis  Agreement  and  shall  remain  in  effect  during  the  free  Trial  Period,  if  any,  and  the  initial  Subscription  Period.  Following  the  expiration  of  the  initial  Subscription  Period,  this  Agreement  shall  be  automatically  renewed  for  subsequent  periods  of  the  same  duration  unless  either  Partygives  written  notice  or  if  Client  fails  to  the  Subscription  Rate  owed.  The  Effective  Date  shall  be  defined  as  the  date  that  Client  has  electronically  agreed  to  this  Agreement.In  the  event  that  Client  and  Company  have  executed  an  Order  Form,  the  Order  Form  shall  dictate  all  the  initial  term,  any  termination  provisions,  and  any  renewals  of  services</p>
                                <h5 className="liq-text-primary">10.2 Termination</h5>
                                <p>Companymay  terminate  this  Agreement  immediately  and  without  prior  notice  in  the  event  of  (a)  non-payment  or  late  payment  by  Client(b)  use  of  the  Licensed  Software  in  a  way  that  Companyreasonably  believes  is  a  violation  of  law,  may  result  in  serious  injury  or  damage  to  any  Partyor  any  non-party,or  (c)  material  violations  of  the  reasonable  rules  of  use  of  the  Licensed  Software  as  promulgated  by  Companyfrom  timetotime.  Either  Party  may  terminate  this  Agreement  by  giving  written  notice  to  the  other  Party.    Client  understands  that  upon  termination,  Client  will  have  access  to  the  Licensed  Software  for  the  remainder  of  the  Subscription  Period  paid  for.    After  such  period,  Client  understands  that  the  Licensed  Software  may  become  immediately  inaccessible  and  any  Client  data  may  be  deleted  or  removed  from  the  Licensed  Software.</p>
                                <h5 className="liq-text-primary">10.3 Exporting  Data</h5>
                                <p>Access  to  Client  dataand  its  authorized  users’  and  guests’access  passwordsfor  the  Licensed  Software  shall  be  disabled  upon  the  final  day  of  the  Subscription  Period  where  either  Party  has  given  written  notice  of  termination,  and  Clientand  its  authorized  users  shall  thereupon  have  no  further  ability  to  access  or  use  the  LicensedSoftware  or  any  Client  data  that  isstored  in  the  Companycomputing  environment.  Companyat  its  sole  discretion  mayretain  all  Client  data  stored  in  Company’s  computing  environment  for  a  period  of  fourteen  (14)  days  after  the  terminationof  this  Agreement,  and  so  long  as  Client  has  paid  all  amounts  due  to  Companydata  available  to  Client  in  an  exportable  formatat  Client's  request  and  expense.  Upon  the  expiration  of  such  fourteen  (14)  day  period,  Client  agrees  that  Company  may  purge  all  Client  data  from  the  Company  computing  environment.</p>
                                <h4 className="liq-text-primary">11. PROPRIETARY  RIGHTS</h4>
                                <h5 className="liq-text-primary">11.1 Infringement  Claim</h5>
                                <p>In  the  event  of  a  claim  that  the  Licensed  Software  or  Client's  use  of  the  Licensed  Software  in  accordance  with  the  terms  of  this  Agreement  infringes  any  proprietary  right  of  any  third  party,  Companyshall  have  the  option,  at  its  own  expense,  to  (a)  obtain  for  Clientthe  right  to  continue  using  the  infringing  item,  (b)  replace  the  infringing  item  or  modify  it  so  that  it  becomes  non-infringing,  or  (c)  terminate  the  Agreementand  licensed  rights  granted  herein.</p>
                                <h5 className="liq-text-primary">11.2 Notice  by  Client</h5>
                                <p>Clientshall  promptly  notify  Companyin  the  event  of  the  threat  or  initiation  of  any  claim,  demand,  action  or  proceeding  to  which  any  infringement  claim  set  forth  abovemay  apply  and  shall  assist  Company,  at  Company's  request  and  expense,  in  the  defense  or  settlement  of  the  matter. </p>
                                <h5 className="liq-text-primary">11.3 Non-Liability</h5>
                                <p>Companyshall  not  be  liable  for  any  alleged  infringement  based  upon  modification  of  the  Licensed  Software  by  anyone  other  than  Companyor  use  of  the Licensed  Software  in  combination  with  other  products  or  services  if  such  claim  would  have  been  avoided  but  for  such  modification  or  combination. </p>
                                <h4 className="liq-text-primary">12. LIMITATION  OF  LIABILITY</h4>
                                <h5 className="liq-text-primary">12.1 Limitations  and  Exclusions.</h5>
                                <p><b>IN  NO  EVENT  SHALL  EITHER  PARTYBE  LIABLE  FOR  LOST  PROFITS,  LOST  BUSINESS,  LOST  DATA,  OR  ANY  OTHER  INDIRECT,  SPECIAL,  INCIDENTAL  OR  CONSEQUENTIAL  DAMAGES  INCURRED  BY  THE  OTHER  PARTYAND  ARISING  OUT  OF  OR  IN  CONNECTION  WITH  THIS  AGREEMENT,  WHETHER  BASED  ON  CONTRACT  (INCLUDING  BUT  NOT  LIMITED  TO  BREACH  OF  WARRANTY)  OR  TORT  (INCLUDING  BUT  NOT  LIMITED  TO  NEGLIGENCE),  EVEN  IF  ADVISED  OF  THE  POSSIBILITY  OF  SUCH  DAMAGES.    CLIENT  IS  RESPONSIBLE  FOR  DETERMINING  WHETHER  THE  LICENSED  SOFTWARE  IS  SUITABLE  FOR  CLIENT’S  INTENDED  USES.</b></p>
                                <h5 className="liq-text-primary">12.2 Maximum  Aggregate  Liability</h5>
                                <p><b>THE  TOTAL  AGGREGATE  LIABILITY  OF  COMPANYUNDER  THIS  AGREEMENT,  WHETHER  ARISING  OUT  OF  BREACH  OF  CONTRACT  (INCLUDING  BUT  NOT  LIMITED  TO  BREACH  OF  WARRANTY)  OR  TORT  (INCLUDING  BUT  NOT  LIMITED  TO  NEGLIGENCE),  SHALL  IN  NO  EVENT  EXCEED  THETOTAL  AMOUNTS  ACTUALLY  PAID  TO  COMPANYBY  CLIENTUNDER  THIS  AGREEMENT.  IN  JURISDICTIONS  WHERE  LIMITATIONS  ARE  PROHIBITED,  THE  MAXIMUM  DAMAGES  SHALL  NOT  EXCEED  THE  STATUTORY  LIMIT.</b></p>
                                <h5 className="liq-text-primary">12.3 Acknowledgment</h5>
                                <p>The  Partiesacknowledge  that  they  have  reached  agreement  on  Subscription  Ratesand  other  charges  set  forth  in  this  Agreement  in  reliance  on  the  disclaimers  of  warranty  and  limitations  and  exclusions  of  liability  set  forth  in  this  Agreement  and  that  the  same  form  an  essential  basis  of  the  bargain  between  the  Parties</p>
                                <h4 className="liq-text-primary">13. GENERAL  TERMS</h4>
                                <h5 className="liq-text-primary">13.1 Assignment</h5>
                                <p>Neither  this  Agreement  nor  any  rights  granted  hereby  may  be  assigned  by  Clientwithout  the  prior  written  consent  of  Company.</p>
                                <h5 className="liq-text-primary">13.2 Modification</h5>
                                <p>This  Agreement  can  only  be  modified  by  a  written  agreement  duly  signed  by  persons  authorized  to  sign  agreements  on  behalf  of  Clientand  of  Company,  and  variance  from  the  terms  and  conditions  of  this  Agreement  in  any  written  notification  given  by  either  Partyshall  have  no  force  or  effect.</p>
                                <h5 className="liq-text-primary">13.3 Severability</h5>
                                <p>If  any  provision  of  this  Agreement  shall  be  held  to  be  invalid,  illegal  or  unenforceable  for  any  reason,  the  validity,  legality  and  enforceability  of  the  remaining  provisions  shall  not  in  any  way  beaffected  or  impaired  thereby.</p>
                                <h5 className="liq-text-primary">13.4 Relationship  of  Parties</h5>
                                <p>Companyand  Clientwill  be  and  shall  act  as  independent  contractors,  and  neither  Partyis  authorized  to  act  as  or  shall  be  an  agent  or  partner  of,  or  joint  venturer  with,  the  other  Partyfor  any  purpose.  Neither  Partyby  virtue  of  this  Agreement  shall  have  any  right,  power,  or  authority  to  act  or  create  any  obligation,  express  or  implied,  on  behalf  of  the  other  Party. </p>
                                <h5 className="liq-text-primary">13.5 Notices</h5>
                                <p>All  notices  shall  be  in  writing  and  shall  be  deemed  tobe  delivered  when  deposited  in  the  United  States  registered  mails,  postage  prepaid,  return  receipt  requested,  or when  sent  by  facsimile  transmission  promptly  confirmed  by  return  transmission,  by  email  read  receipt  requested.  All  notices  shall  be  directed  to  Clientor  Companyat  the  respective  addresses  set  forth  belowor  to  such  other  address  as  either  Partymay,  from  time  to  time,  designate  by  notice  to  the  other  Party.</p>
                                <h5 className="liq-text-primary">13.6 Injunctive  Relief</h5>
                                <p>In  the  event  that  (a)  Clientor  any  of  its  members  or  guestsattempts  or  threatens  to  use,  copy,  license,  or  convey  the  items  supplied  by  Companyhereunder  in  a  manner  contrary  to  the  terms  of  this  Agreement,  or  (b)  either  Partyattempts  or  threatens  to  violate  its  obligations  under  Section  9,  the  aggrieved  Partyshall  have,  in  addition  to  any  other  remedies  available  to  it,  the  right  to  injunctive  relief.    Each  Partyhereby  acknowledges  that  other  remedies  at  law  are  inadequate  in  the  circumstances  set  forth  herein. </p>
                                <h5 className="liq-text-primary">13.7 Governing  Law</h5>
                                <p>This  Agreement,  and  any  and  all  tort  claims  that  may  arise  in  connection  with  the  Licensed  Software  and  any  related  services,  will  be  governed  by  the  substantive  laws  of  the  State  of  Californiabecause  that  is  the  state  in  which  Companyhas  its  main  office.</p>
                                <h5 className="liq-text-primary">13.8 Force  Majeure</h5>
                                <p>Except  for  the  Client’s  failure  to  make  required  payments,  neither  Partyshall  be  liable  for  any  damages  or  penalty  for  any  delay  in  performance  of,  or  failure  to  perform,  any  obligation  hereunder  or  for  failure  to  give  the  other  Partyprior  notice  thereof  when  such  delay  or  failure  is  due  to  the  elements,  acts  of  God,  government  regulation,  political  instability,  acts  of  war,  acts  of  terrorism,  power  outages,  changes  in  law,  internet  disruptionor  other  causes  beyond  that  Party's  reasonable  control.</p>
                                <h5 className="liq-text-primary">13.9 Non-Waivers</h5>
                                <p>No  express  or  implied  waiver  by  either  Partyof  any  event  of  default  hereunder  shall  in  any  way  be,  or  be  construed  as,  a  waiver  of  any  future  or  subsequent  event  of  default. </p>
                                <h5 className="liq-text-primary">13.10 Survival</h5>
                                <p>Provisions  that  would  be  reasonably  believed  to  survive  termination  of  this  Agreement  shall  survive  including  but  not  limited  to  sections  2,3,4,5,6,7,8,9,10,11,12  and  13.</p>
                                <h5 className="liq-text-primary">13.11 Entire  Agreement.</h5>
                                <p>The  Partiesacknowledge  that  this  Agreement,  together  with  the  anyother  Additional  Agreements,Privacy  Policies,  and  Terms  of  Useset  forth  the  complete,  exclusive  and  integrated  understanding  of  the  Partieswhich  supersedes  all  proposals  or  prior  agreements,  oral  or  written,  and  all  other  prior  communications  between  the  Partiesrelating  to  the  subject  matter  of  this  Agreement.    In  the  event  that  this  Agreement  conflicts  with  any  Additional  Agreements,  this  Agreement  shall  control  and  prevail.</p>
                                <h5 className="liq-text-primary">13.12 Exportand  Electronic  Notices</h5>
                                <p>Clientshall  not  export  or  re-export  the  Licensed  Software  in  violation  of  U.S.  export  laws.  The  communications  between  Client    andCompany  may  use  electronic  means  via  the  Licensed  Software.    For  contractual  purposes,  Client  (1)  consents  to  receive  communications  from  Company  in  an  electronic  form;  and  (2)  agrees  that  all  terms,  conditions,  agreements,  notices,  disclosures,  and  othercommunications  that  Company  provides  to  Client  electronically  satisfy  any  legal  requirement  that  such  communications  would  satisfy  if  it  were  to  be  in  writing. </p>
                                <h5 className="liq-text-primary">13.13 Claims  must  be  filed  within  one  year</h5>
                                <p>To  the  extent  permitted  by  law,  any  claimrelated  to  this  Agreement  or  the  Licensed  Softwaremust  be  brought  within  one  year.  The  one-year  period  begins  on  the  date  when  the  claim  first  could  be  filed.  Any  claim  that  is  not  filed Lead  IQ,  Inc.SAAS  AgreementPage  11within  that  time  is  permanently  barred.  This  section  applies  to  thePartiessuccessorsor  assigns  as  permitted.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default MasterServiceAgreement;