import React from 'react';
import { Link } from "react-router-dom";

class TermsOfUse extends React.Component {

    componentDidMount() {
        window.scrollTo(0, 0)
    }

    render() {
        return (
            <div>
                <div>
                    <div className="privacy-Cover">
                        <div className="container prospectHeaderTitle">
                            <section className="pt-5 gettingStarted">
                                <h1 className="text-white text-center mb-4 fa-2x prospectText"><b>Terms of Use</b></h1>
                            </section>
                        </div>
                    </div>
                    <div className="faq-waveDesign">
                        <img src="/img/wave-four.png" className="img-fluied faq-waveDesignProspect" style={{zIndex: 1}} alt="Wave" />
                    </div>
                    <div className="terms-bg">
                        <div className="container terms-container">
                            <div className="card" style={{ zIndex: 3 }}>
                                <div className="card-body card-blog">
                                    <h4><mark className="liq-text-primary">Your Acceptance</mark></h4>
                                    <p>Welcome to the Terms of Use for the LeadIQ website (www.leadiq.com). This is an agreement (“Agreement”) between LeadIQ, Inc. (“LeadIQ”), the owner and operator of www.leadiq.com and any services offered via the Site (collectively the “Site”) and you (“you”, “your” or “user(s)”), a user of the Site.</p>
                                    <p>Throughout this Agreement, the words “LeadIQ,” “us,” “we,” and “our,” refer to our company, LeadIQ, Inc., as is appropriate in the context of the use of the words</p>
                                    <p>By clicking “I agree” or accessing the Site you agree to be bound by this Agreement and the Privacy Policy. We may amend this Agreement at any time and may notify you if we do so. PLEASE BE AWARE THAT THIS AGREEMENT CONTAINS CLASS ACTION AND ARBITRATION PROVISIONS THAT MAY AFFECT YOUR RIGHTS.</p>
                                    <h4><mark className="liq-text-primary">Privacy</mark></h4>
                                    <p>Please read LeadIQ’s Privacy Policy for more information regarding our collection and use of your information.</p>
                                    <h4><mark className="liq-text-primary">Login and Sign-up</mark></h4>
                                    <p>Portions of the Site may require you to create a login or sign-up for an account. You must fully complete the registration process by providing us with your current, complete, truthful, and accurate information as prompted by the applicable registration form. In order to complete your sign-up, we may require you to agree to Additional Agreements (defined below). Upon sign-up LeadIQ may assign you a username and password where required. You are entirely responsible for maintaining the confidentiality of your password and account and for any and all activities that occur under your account. You agree to notify LeadIQ immediately of any unauthorized use of your account or any other breach of security. LeadIQ will not be liable for any losses you incur as a result of someone else using your password or account, either with or without your knowledge. However, you could be held liable for losses incurred by LeadIQ or another party due to someone else using your account or password. You may not use anyone else’s account at any time, without the permission of the account holder. All users must be over the age of 18 and have the legal capacity to enter into a binding agreement. We reserve the right to restrict or refuse sign-up for any users of the Site for any reason whatsoever.</p>
                                    <h4><mark className="liq-text-primary">Site Availability and Modification</mark></h4>
                                    <p>Although we will attempt to provide continuous Site availability to you, we do not guarantee that the Site will always be available, work, or be accessible at any particular time. We reserve the right to alter, modify, update, or remove our Site at any time. We may conduct such modifications to our Site for security reasons, intellectual property, legal reasons, or various other reasons at our discretion, and we are not required to explain such modifications. For example, we may provide updates to fix security flaws, or to respond to legal demands. Please note that this is a non-binding illustration of how we might exercise our rights under this section, and nothing in this section obligates us to take measures to update the Site for security, legal, or other reasons.</p>
                                    <h4><mark className="liq-text-primary">Additional Agreements</mark></h4>
                                    <p>In order to access some portions of the Site or some services offered via the Site, you may be required to agree and execute a LeadIQ SAAS services agreement or other relevant agreements (collectively “Additional Agreements”) as required by LeadIQ. The Additional Agreements should be read in conjunction with this Agreement and may obligate you to additional responsibilities when using the Site. If you wish to learn more about any LeadIQ services, please contact us at support@leadiq.com.</p>
                                    <h4><mark className="liq-text-primary">Third Party Links</mark></h4>
                                    <p>The Site may contain links to third party websites that are not owned or controlled by LeadIQ. LeadIQ has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, LeadIQ will not and cannot censor or edit the content of any third-party site. By using the Site, you expressly relieve LeadIQ from any and all liability arising from your use of any third-party website.</p>
                                    <h4><mark className="liq-text-primary">Your License</mark></h4>
                                    <p>By accepting this Agreement, we grant you a personal, non-exclusive, revocable, limited license to access our Site as provided by us. This license is subject to your compliance with this Agreement and any other Additional Agreements. Please be aware that this license does not grant you any ownership interest in any portions of the Site or to any copyrighted content found on the Site. Such copyrights and intellectual property rights are owned solely by LeadIQ or its third party licensors. Subject to anything to the contrary in this Agreement or any other Additional Agreements, we may revoke your license to access the Site at any time and without notice.</p>
                                    <h4><mark className="liq-text-primary">Your Conduct While Using The Site</mark></h4>
                                    <p>When accessing or using our Site, you are solely responsible for your use and for any use of the LeadIQ Site made using your account. You agree to abide by the following rules of conduct:</p>
                                    <label className="mb-0">You will not copy, distribute or disclose any part of the Site in any medium, including without limitation by any automated or non-automated “scraping”;</label>
                                    <label className="mb-0">You will not attempt to interfere with, compromise the system integrity or security, or decipher any transmissions to or from the servers running the Site;</label>
                                    <label className="mb-0">You will not use any robot, spider, crawler, scraper or other automated means or interface not provided by us to access the Site or to extract or export data collected through the Site;</label>
                                    <label className="mb-0">You will not take any action that imposes, or may impose at our sole discretion, an unreasonable or disproportionately large load on our infrastructur</label>
                                    <label className="mb-0">You agree not to use the Site to stalk, harass, bully or harm another individual;</label>
                                    <label className="mb-0">You agree that you will not hold LeadIQ responsible for your use of the Site;</label>
                                    <label className="mb-0">You agree not to violate any requirements, procedures, policies or regulations of networks connected to LeadIQ;</label>
                                    <label className="mb-0">You agree not to interfere with or disrupt the Site;</label>
                                    <label className="mb-0">You agree to not violate any federal or state laws within the US while using the Site;</label>
                                    <label className="mb-0">You agree not to use the Site in any way that is: misleading, unlawful, defamatory, obscene, invasive, threatening, or harassing.</label>
                                    <p>If you are discovered to be undertaking any of the aforementioned actions your privileges to use our Site may at our discretion be terminated or suspended. Generally, we will provide an explanation for any suspension or termination of your use of any of our Site, but LeadIQ reserves the right to suspend or terminate any account at any time without notice or explanation.</p>
                                    <h4><mark className="liq-text-primary">Your Content</mark></h4>
                                    <p>Your ability to submit or transmit any information through the Site, including but not limited to text, audio messages, videos, photos, images or any other information will be referred to as “User Content” throughout this Agreement. You are solely responsible for any User Content submitted to the Site. When you submit any User Content to us, you grant LeadIQ, its partners, affiliates, users, representatives and assigns a non-exclusive, fully-paid, royalty-free, irrevocable, world-wide, universal, transferable, assignable license to display, publicly perform, distribute, store, broadcast, transmit, reproduce, modify, prepare derivative works and otherwise use and reuse all or part of your User Content. Additionally, you agree that LeadIQ may use User Content, in an aggregated form from which all personally identifiable information has been removed, for purposes of benchmarking system performance, preparing statistics and system metrics, marketing and other purposes.</p>
                                    <h4><mark className="liq-text-primary">Intellectual Property</mark></h4>
                                    <p>The name “LeadIQ,” the design of the LeadIQ Site along with LeadIQ created text, writings, images, templates, scripts, graphics, interactive features and the trademarks, marks and logos contained therein (“Marks”), are owned by or licensed to LeadIQ. The Marks are subject to copyright and other intellectual property rights under US laws and international conventions. LeadIQ reserves all rights not expressly granted in and to the Site. You agree to not engage in the use, copying, or distribution anything contained within the Site or Site unless we have given you express written permission.</p>
                                    <h4><mark className="liq-text-primary">Idea Submission</mark></h4>
                                    <p>LeadIQ or any of its employees do not accept or consider unsolicited ideas, including but not limited to ideas relating to processes, technologies, product enhancements, or product names. Please do not submit any unsolicited ideas, content, artwork, suggestions, or other works (“Submissions”) in any form to LeadIQ. The sole purpose of this policy is to avoid potential misunderstandings or disputes when LeadIQ’s products might seem similar to ideas you submitted to LeadIQ. If, despite our request that you not send us your ideas, you agree to the following: (1) your Submissions and their contents will automatically become the property of LeadIQ, without any compensation to you; (2) LeadIQ may use or redistribute the Submissions and their contents for any purpose and in any way; (3) there is no obligation for LeadIQ to review the Submission; and (4) there is no obligation to keep any Submissions confidential.</p>
                                    <h4><mark className="liq-text-primary">Payments</mark></h4>
                                    <p>Sections 12 to 15 shall control any payments and refunds offered via the Site, unless you have executed any Additional Agreements with LeadIQ. You agree that we may charge your selected method of payment at the time of checkout for any services offered on the Site. Your credit card information will be shared with our third party payment processor. By purchasing anything from our Site you also agree to the terms and conditions of our third party payment processor. Please be aware that all payment information will be stored and secured by the payment processor and not us, and you must agree with our payment processor’s policies before paying for any portions of the Site.</p>
                                    <h4><mark className="liq-text-primary">Monthly Payments</mark></h4>
                                    <p>In order to use and access portions of the Site, you may be required to pay a monthly fee as listed on the Site. You agree to pay the monthly fee listed on the Site upon sign-up. Please be aware that our fees are billed monthly. YOU HEREBY AGREE AND AUTHORIZE US TO BILL YOU ON A MONTHLY BASIS AND AGREE THAT NO ADDITIONAL CONSENT IS REQUIRED BY YOU TO CHARGE YOUR PREFERRED PAYMENT METHOD AUTOMATICALLY EACH MONTH.</p>
                                    <h4><mark className="liq-text-primary">Refunds</mark></h4>
                                    <p>At LeadIQ we want you to be satisfied with any services offered. Therefore, we offer a 15-day refund policy from the date of your initial date of payment. If you are not satisfied with any of the services offered via the Site within fifteen (15) days of your initial payment, please contact us at support@leadiq.com and we’ll gladly refund your unused credits minus any fees. For all refunds there may be additional processing time with your credit card company that may delay the posting of a credit to your account.</p>
                                    <h4><mark className="liq-text-primary">Termination</mark></h4>
                                    <p>You may cancel your use of the Site and any services offered at any time via your account dashboard by contacting us and giving a 30 days written notice at support@leadiq.com. Please be aware that upon termination of your account, access to portions of our Site may be become immediately disabled and any User Content stored on the Site may be deleted immediately. Upon termination you will not be entitled to any refunds or proration of any fees paid except as stated in this Agreement. We may terminate your account if we determine that: (1) you have violated any applicable laws while using our Site; (2) if you have violated this Agreement or any other of our Site policies; (3) after you have used any and all credits purchased via the Site; or (4) if we believe that any of your actions may harm LeadIQ, at our sole decision or discretion. In the event of termination, we will strive to provide you with a timely explanation; however, we are not required to do so.</p>
                                    <h4><mark className="liq-text-primary">Site Disclaimer</mark></h4>
                                    <p>Although we aim to provide you accurate data and content through the Site, please be aware that our Site and any information found within it are offered “as-is” and with all faults. While we strive to provide a great user experience for all of our users, LeadIQ assumes no responsibility for the temporary unavailability of the Site or the timeliness, transport, outage, deletion, failure to deliver or failure to store/retrieve any user commands, data, communications, or personalization settings in connection with LeadIQ. You agree that any information may be inaccurate, unsubstantiated or possibly even incorrect. We cannot guarantee that using our Site will result in any benefits or positive results for you. Unless otherwise stated, you agree to release us from any liability that we may have to in relation to your use of our Site.</p>
                                    <h4><mark className="liq-text-primary">Limitation of Liability; Representations and Warranties</mark></h4>
                                    <p>We try to keep our Site safe, secure, and properly functioning, but we cannot guarantee the continuous operation of or access to our Site. You agree that you are making use of our Site at your own risk, and that they are being provided to you on an “AS IS,” “WITH ALL FAULTS,” and “AS AVAILABLE” basis. Accordingly, to the extent permitted by applicable law, we exclude all express or implied warranties, terms and conditions including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, freedom from viruses, and non-infringement.</p>
                                    <p>To the extent permitted by applicable law, we (including OUR officers, directors, agents, AFFILIATES and employees) are not liable, and you agree not to hold us responsible, for any damages or losses (including, but not limited to, loss of money, goodwill or reputation, profits, or other intangible losses or any special, indirect, or consequential damages) resulting directly or indirectly from your use of the Site or any of its related services WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. Some jurisdictions do not allow the disclaimer of warranties or exclusion of damages, so such disclaimers and exclusions may not apply to you. WHERE ALLOWED OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED One-hundred dollars (USD) or the total amount you have paid to us within the past six months, whichever is greater. Specifically, in those jurisdictions not allowed, we do not disclaim liability for: (a) death or personal injury caused by LeadIQ’s negligence or that of any of its officers, employees or agents; (b) fraudulent misrepresentation; or (c) any liability which it is not lawful to exclude either now or in the future.</p>
                                    <h4><mark className="liq-text-primary">Indemnity</mark></h4>
                                    <p>You agree to defend, indemnify and hold harmless LeadIQ, Inc., its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from:</p>
                                    <p>your use of and access to the LeadIQ Site; your violation of any term of this Agreement; or any claim that your use of the Site harmed a third party.</p>
                                    <p>This defense and indemnification obligation will survive this Agreement and your use of the LeadIQ Site. You also agree that you have a duty to defend us against such claims and we may require you to pay for an attorney(s) of our choice in such cases. You agree that this indemnity extends to requiring you to pay for our reasonable attorneys’ fees, court costs, and disbursements. In the event of a claim such as one described in this paragraph, we may elect to settle with the party/parties making the claim and you shall be liable for the damages as though we had proceeded with a trial.</p>
                                    <h4><mark className="liq-text-primary">Copyrights</mark></h4>
                                    <p>We take copyright infringement very seriously, and we shall comply with the Digital Millennium Copyright Act. If you live within the US or own any copyrighted material within the US and believe that your copyright has been infringed, please send us a message which contains:</p>
                                    <label className="mb-0">Your name.</label>
                                    <label className="mb-0">The name of the party whose copyright has been infringed, if different from your name.</label>
                                    <label className="mb-0">The name and description of the work that is being infringed.</label>
                                    <label className="mb-0">The location on our website of the infringing copy.</label>
                                    <label className="mb-0">A statement that you have a good faith belief that use of the copyrighted work described above is not authorized by the copyright owner (or by a third party who is legally entitled to do so on behalf of the copyright owner) and is not otherwise permitted by law.</label>
                                    <label className="mb-0">A statement that you swear, under penalty of perjury, that the information contained in this notification is accurate and that you are the copyright owner or have an exclusive right in law to bring infringement proceedings with respect to its use.</label>
                                    <p>You must sign this notification and send it to our Copyright Agent: Copyright Agent of LeadIQ, support@leadiq.com.</p>
                                    <h4><mark className="liq-text-primary">Age Compliance</mark></h4>
                                    <p>The Site may only be used by persons 18 years and older. If you are under 18 please stop using our Site and please do not submit any information to us.</p>
                                    <h4><mark className="liq-text-primary">Choice of Law</mark></h4>
                                    <p>This Agreement shall be governed by the laws in force in the state of California. The offer and acceptance of this contract is deemed to have occurred in the state of California.</p>
                                    <h4><mark className="liq-text-primary">Arbitration</mark></h4>
                                    <p>You agree that any dispute relating in any way to your use of the Site shall be submitted to confidential arbitration in Santa Clara County, California. Arbitration under this Agreement shall be conducted pursuant to the applicable rules (“Rules”) then prevailing at the American Arbitration Association. Arbitration shall be conducted by one (1) arbitrator as selected pursuant to the Rules; the arbitrator’s award shall be final and binding and may be entered as a judgment in any court of competent jurisdiction. Each party shall be responsible for their own arbitration fees and costs. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class action proceedings or otherwise. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of, related to or connected with the use of the Site or this Agreement must be filed within one (1) year after such claim or cause of action arose or be forever banned. In the event that the law does not permit the abovementioned dispute to be resolved through arbitration, you agree that any actions shall be brought solely in a court of competent jurisdiction located within or otherwise nearest to Santa Clara County, CA.</p>
                                    <h4><mark className="liq-text-primary">Class Action Waiver</mark></h4>
                                    <p>You and LeadIQ agree that any proceedings to resolve or litigate any dispute whether through a court of law or arbitration shall be solely conducted on an individual basis. You agree that you will not seek to have any dispute heard as a class action, representative action, collective action, or private attorney general action.</p>
                                    <h4><mark className="liq-text-primary">Force Majeure</mark></h4>
                                    <p>You agree that we are not responsible to you for anything that we may otherwise be responsible for, if it is the result of events beyond our control, including, but not limited to, acts of God, war, insurrection, riots, terrorism, crime, labor shortages (including lawful and unlawful strikes), embargoes, postal disruption, communication disruption, failure or shortage of infrastructure, shortage of materials, or any other event beyond our control.</p>
                                    <h4><mark className="liq-text-primary">Severability</mark></h4>
                                    <p>In the event that a provision of this Agreement is found to be unlawful, conflicting with another provision of the Agreement, or otherwise unenforceable, the Agreement will remain in force as though it had been entered into without that unenforceable provision being included in it.</p>
                                    <p>If two or more provisions of this Agreement or any other agreement you may have with LeadIQ are deemed to conflict with each other’s operation, you agree that LeadIQ shall have the sole right to elect which provision remains in force.</p>
                                    <h4><mark className="liq-text-primary">Non-Waiver</mark></h4>
                                    <p>We reserve all rights permitted to us under this Agreement as well as under the provisions of any applicable law. Our non-enforcement of any particular provision or provisions of this Agreement or any applicable law should not be construed as our waiver of the right to enforce that same provision under the same or different circumstances at any time in the future.</p>
                                    <h4><mark className="liq-text-primary">Assignment</mark></h4>
                                    <p>You may not assign your rights and/or obligations under this Agreement to any other party without our prior written consent. We may assign our rights and/or obligations under this Agreement to any other party at our discretion.</p>
                                    <h4><mark className="liq-text-primary">Amendments</mark></h4>
                                    <p>We may amend this Agreement from time to time. When we amend this Agreement, we will update this page and indicate the date that it was last modified or we may email you. You may refuse to agree to the amendments, but if you do, you must immediately cease using our Site.</p>
                                    <h4><mark className="liq-text-primary">Electronic Communications</mark></h4>
                                    <p>The communications between you and LeadIQ use electronic means, whether you visit the Site or send LeadIQ e-mails, or whether LeadIQ posts notices on the Site or communicates with you via e-mail. For contractual purposes, you (1) consent to receive communications from LeadIQ in an electronic form; and (2) agree that all terms, conditions, agreements, notices, disclosures, and other communications that LeadIQ provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing. The foregoing does not affect your statutory rights.</p>
                                    <h4><mark className="liq-text-primary">California Users</mark></h4>
                                    <p>Pursuant to California Civil Code Section 1789.3, any questions about pricing, complaints, or inquiries about LeadIQ must be sent to our agent for notice to: <Link to="/">support@leadiq.com</Link>.</p>
                                    <p>Lastly, California users are also entitled to the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.</p>
                                    <p>Last updated on May 17, 2016</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            );
        }
        }
                                                    
export default TermsOfUse;